title: "HIGHERPROJECT"
description: ""
github_username: BridgeDeck

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - downloads.md
  - roadmap.md
  - usermanual.md

# footer : '<a href="https://github.com/Higher-Project-GAME">HIGHER PROJECT</a>'

# set the size of the text to 'large' or 'small', default is small
font-size: small
